name: fastlane build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build schemes
    strategy:
      matrix:
        platform:
          - tvOS
          - iOS
          
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install Carthage
        run: "carthage update"
      - uses: mxcl/xcodebuild@v1
        with:
          xcode: ^12
          platform: ${{ matrix.platform }}
          action: build             # default = `test`
          code-coverage: true       # default = `false`
          warnings-as-errors: true  # default = `false`
          configuration: release    # no default, ie. `xcodebuild` decides itself
      
