name: fastlane build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Carthage
        run: "carthage update"
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: JellyfinPlayer.xcodeproj
          scheme: JellyfinPlayer
          destination: platform=iOS
          action: build
