name: "Lint 🧹"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Lint 🧹"
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Run SwiftLint
        run: swiftlint autocorrect
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: '.'
          author_name: jellyfin-bot
          author_email: team@jellyfin.org
          default_author: github_actor
          message: 'Auto lint'
          pull_strategy: '--no-rebase'
          push: true
