name: "Lint 🧹"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Lint 🧹"
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run SwiftLint
        run: swiftlint --fix
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: '.'
          author_name: acvigue
          author_email: acvigue@me.com
          default_author: user_info
          message: 'Auto lint'
          pull_strategy: '--no-rebase'
          push: true
