name: "Lint 🧹"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Lint 🧹"
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Run SwiftLint
        run: swiftlint --fix
        
      - name: Commit new changes to the repo
        run: |
          git config user.name jellyfin-bot
          git config user.email team@jellyfin.org
          git pull
          git add .
          git commit -m "auto lint" || echo
          git push
